version: v34.12.6

files:
  - .github/workflows/codeql-analysis.yaml
  - .github/workflows/close-stale-prs.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/renovate_dependency_management.yaml

values:
  runWizCliDepsScan: false
  renovateCronjobSchedule: "40 7 * * 1-5" # This is UTC -> At 08:40 CET / 09:40 CEST on every day-of-week from Monday through Friday.
